version: "3.9"
services:
  schoolnotify:
    image: nekogravitycat/schoolnotify:latest
    container_name: schoolnotify
    restart: on-failure
    expose:
      - "5000"
    environment:
      - GUNICORN_CMD_ARGS="-b 0.0.0.0:5000"
      - TZ=Asia/Taipei
    env_file:
      - ./.env/schoolnotify.env
  schoolnotify-nginx:
    build: nginx
    container_name: schoolnotify-nginx
    restart: on-failure
    expose:
      - 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - schoolnotify
  schoolnotify-cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: schoolnotify-cloudflared
    restart: on-failure
    command: tunnel run
    env_file:
      - ./.env/cloudflared.env
    depends_on:
      - schoolnotify-nginx
