version: "3.9"
services:
  schoolnotify:
    image: ghcr.io/nekogravitycat/schoolnotify
    ports:
      - "80:80"
    env_file:
      - schoolnotify.env
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - nginx.env
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - schoolnotify
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx/user_conf.d:/etc/nginx/user_conf.d
volumes:
  nginx_secrets:
