version: "3.9"
services:
  schoolnotify:
    image: ghcr.io/nekogravitycat/schoolnotify:master
    container_name: schoolnotify
    restart: unless-stopped
    expose:
      - "5000"
    environment:
      - GUNICORN_CMD_ARGS="-b 0.0.0.0:5000"
    env_file:
      - schoolnotify.env
  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    expose:
      - "80"
      - "1337"
    depends_on:
      - schoolnotify
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    env_file:
      - cloudflared.env
    depends_on:
      - nginx
